/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.68
 * Generated at: 2021-09-06 08:35:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class aside_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1627018532952L));
    _jspx_dependants.put("jar:file:/D:/A_TeachingMaterial/6.JspSpring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp3/wtpwebapps/camb/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"aside\" style=\"float:left;clear:both;\">\r\n");
      out.write("<aside class=\"main-sidebar\">\r\n");
      out.write("        <!-- Sidebar -->\r\n");
      out.write("        <ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\" id=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar - Brand -->\r\n");
      out.write("            <a class=\"sidebar-brand d-flex align-items-center justify-content-center\" href=\"/resources/sbadmin/index.html\">\r\n");
      out.write("                <div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("                    <i class=\"fas fa-laugh-wink\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-brand-text mx-3\">CAM <sup>B</sup></div>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider my-0\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Dashboard -->\r\n");
      out.write("            <li class=\"nav-item active\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-tachometer-alt\"></i>\r\n");
      out.write("                    <span>CamB 소개</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Heading -->\r\n");
      out.write("            <div class=\"sidebar-heading\">\r\n");
      out.write("                	USER\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"/resources/sbadmin/#\" data-toggle=\"collapse\" data-target=\"#STUDENT\" aria-expanded=\"true\" aria-controls=\"collapseTwo\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-users\"></i>\r\n");
      out.write("                    <span>STUDENT</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"STUDENT\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/buttons.html\">학적</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">수강신청</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">수업</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">등록금</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">장학</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">졸업</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">봉사</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">상담</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">생활관</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">정보화시설</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">증명서</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"/resources/sbadmin/#\" data-toggle=\"collapse\" data-target=\"#PROFESSOR\" aria-expanded=\"true\" aria-controls=\"collapseTwo\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-user\"></i>\r\n");
      out.write("                    <span>PROFESSOR</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"PROFESSOR\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\" >\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <a class=\"collapse-item\" data-toggle=\"collapse\" data-target=\"#PROFESSOR_menu\" href=\"#\">수업관리</a>\r\n");
      out.write("                        <a class=\"collapse-item\" data-toggle=\"collapse\" data-target=\"#PROFESSOR_consulting\" href=\"#\">학생별 상담 관리</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/professor/salary/salaryList\">급여</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/professor/academic/academicList\">승인</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"#\">증명서</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"PROFESSOR_menu\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("	               	 <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("	               	 	<a class=\"collapse-item\" data-toggle=\"collapse\" data-target=\"#PROFESSOR\" href=\"#\" style=\"box-shadow: 1px 1px 3px 1px #dadce0;\">수업관리</a>\r\n");
      out.write("	               	 	<div style=\"box-shadow: 1px 1px 3px 2px gray inset;\">\r\n");
      out.write("		               	 	<a class=\"collapse-item\" href=\"/professor/list\">수업 조회</a>\r\n");
      out.write("		               	 	<a class=\"collapse-item\" href=\"#\">시간표 조회</a>\r\n");
      out.write("		               	 	<a class=\"collapse-item\" href=\"/professor/attendance/list\">출결 관리</a>\r\n");
      out.write("		               	 	<a class=\"collapse-item\" href=\"/professor/grade/list\">성적 관리</a>\r\n");
      out.write("		               	 	<a class=\"collapse-item\" href=\"/professor/study/lectureEvaluationList\">강의평가 조회</a>\r\n");
      out.write("	               	 	</div>\r\n");
      out.write("	               	 </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"PROFESSOR_consulting\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("	               	 <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("	               	 	<a class=\"collapse-item\" data-toggle=\"collapse\" data-target=\"#PROFESSOR\" href=\"#\" style=\"box-shadow: 1px 1px 3px 1px #dadce0;\">학생별 상담 관리</a>\r\n");
      out.write("	               	 	<div style=\"box-shadow: 1px 1px 3px 2px gray inset;\">\r\n");
      out.write("		               	 	<a class=\"collapse-item\" href=\"/professor/consulting/consultingList\">상담 일정 조회</a>\r\n");
      out.write("		               	 	<a class=\"collapse-item\" href=\"#\">상담 통계</a>\r\n");
      out.write("	               	 	</div>\r\n");
      out.write("	               	 </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"/resources/sbadmin/#\" data-toggle=\"collapse\" data-target=\"#ADMIN\" aria-expanded=\"true\" aria-controls=\"collapseTwo\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-key\"></i>\r\n");
      out.write("                    <span>ADMIN</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"ADMIN\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/buttons.html\">사용자</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">수업</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">등록</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">학적</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">학사 일정 관리</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">학과 관리</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">증명서 관리</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">급여</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">공지사항</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">Q&A</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">FAQ</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">시설관리</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">봉사관리</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">마일리지</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/cards.html\">장학금</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Heading -->\r\n");
      out.write("            <div class=\"sidebar-heading\">\r\n");
      out.write("                Addons\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link collapsed\" href=\"/resources/sbadmin/#\" data-toggle=\"collapse\" data-target=\"#collapsePages\" aria-expanded=\"true\" aria-controls=\"collapsePages\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-folder\"></i>\r\n");
      out.write("                    <span>COMMON</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"collapsePages\" class=\"collapse\" aria-labelledby=\"headingPages\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/login.html\">메인 위젯 설정</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/register.html\">캘린더</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/resources/sbadmin/forgot-password.html\">공지사항</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider d-none d-md-block\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar Toggler (Sidebar) -->\r\n");
      out.write("            <div class=\"text-center d-none d-md-inline\">\r\n");
      out.write("                <button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar Message -->\r\n");
      out.write("            <div class=\"sidebar-card d-none d-lg-flex\">\r\n");
      out.write("                <img class=\"sidebar-card-illustration mb-2\" src=\"/resources/sbadmin/img/undraw_rocket.svg\" alt=\"...\">\r\n");
      out.write("                <p class=\"text-center mb-2\">\r\n");
      out.write("                	<strong>Cam B</strong> 를 방문해주셔서 감사합니다!\r\n");
      out.write("                </p>\r\n");
      out.write("                <a class=\"btn btn-success btn-sm\" href=\"/resources/sbadmin/https://startbootstrap.com/theme/sb-admin-pro\">마이페이지 가기</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("        <!-- End of Sidebar -->\r\n");
      out.write("       </aside>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
